config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do
    root 'welcome#index'
    resource :about, only: :show
    resource :gallery, only: :show

    resources :contacts, only: [:index, :create]
    
    namespace :admin do
      root 'dashboard#index'

      resources :settings, only: [:index, :edit, :update]
      resources :contacts, only: [:index, :show, :destroy]
      resources :pages, only: [:index, :show, :edit, :update]
      resources :projects
    end
  end
end

app/views/admin/pages/_form.html.slim
= simple_form_for [:admin, @page] do |f|
  = f.input :title
  = f.input :content, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full' } }

  = f.submit class: 'btn btn-secondary'

app/views/admin/pages/edit.html.slim
- breadcrumbs([{text: 'Сторінки', url: admin_pages_path}, {text: 'Редагування'}])

.row
  .col-lg-12
    = render 'admin/pages/form'

app/views/admin/pages/index.html.slim
- breadcrumbs({text: 'Сторінки'})

.row
  .col-lg-12
    .table-responsive
      table.table.table-bordered.table-hover
        thead
          tr
            th Загаловок
            th Текст
            th Дії
        tbody
          - @pages.all.each do |page|
            tr
              td = page.title
              td = truncate_html(page.content)
              td
                => link_to admin_page_path(page)  do
                  = fa_icon 'eye', text: 'Перегляд'
                |&nbsp;&nbsp;&nbsp;
                =< link_to edit_admin_page_path(page) do
                  = fa_icon 'pencil', text: 'Редагувати'


app/views/admin/pages/show.html.slim
- breadcrumbs([{text: 'Сторінки', url: admin_pages_path}, {text: @page.title}])

.row
  .col-lg-12
    .table-responsive
      table.table.table-bordered.table-hover
        tbody
          tr
            td Заголовок
            td = @page.title
          tr
            td Текст
            td = @page.content.html_safe