config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do
    root 'welcome#index'
    resource :about, only: :show
    resource :gallery, only: :show

    resources :contacts, only: [:index, :create]
    
    namespace :admin do
      root 'dashboard#index'

      resources :settings, only: [:index, :edit, :update]
      resources :contacts, only: [:index, :show, :destroy]
      resources :pages, only: [:index, :show, :edit, :update]
      resources :projects
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/views/welcome/index.html.slim
.wrapper-area
  .slider4-area
    .bend.niceties.preview-1
      #nivoslider.slides
        = image_tag "slider-1/4-1.jpg", alt: "slider", title: "#slider_caption"
      #slider_caption.t-cn.slider-direction
        .slider-content.s-tb.slider-1
          .title-container.s-tb-c
            - if en_locale?
              span LLC Perspective-IV
              h1.title1 Providing landscape services
              .slider-btn-area
                = link_to 'Read More', about_path, class: 'btn-slider-fill'
            - else
              span ТОВ "Перспектива-ІВ"
              h1.title1 Надання ландшафтних послуг
              .slider-btn-area
                = link_to 'Дізнатися більше', about_path, class: 'btn-slider-fill'
      
  /! Slider 4 Area End Here
  /! Service 4 Area Start Here
  .service4-area
    .container
      .section-title-area.col-xs-12
        h2.section-title
          - if en_locale?
            span< W
            |hat
            span< W
            |e
            span< O
            |ffer
          - else
            span< Щ
            |о
            span< М
            |и
            span< П
            |ропонуємо
        .title-bottom-icon
          i.fa.fa-tree aria-hidden="true" 
    .container
      .row
        .col-lg-4.col-md-4.col-sm-4.col-xs-12
          .service-box
            span
              i.fa.fa-pagelines aria-hidden="true" 
            h3
              a href="#" = Page['home_landscape'].title
            p = Page['home_landscape'].content.html_safe
            
        .col-lg-4.col-md-4.col-sm-4.col-xs-12
          .service-box
            span
              i.fa.fa-pagelines aria-hidden="true" 
            h3
              a href="#" = Page['home_sports_grounds'].title
            p = Page['home_sports_grounds'].content.html_safe
            
        .col-lg-4.col-md-4.col-sm-4.col-xs-12
          .service-box
            span
              i.fa.fa-pagelines aria-hidden="true" 
            h3
              a href="#" = Page['home_game_grounds'].title
            p = Page['home_game_grounds'].content.html_safe
            
  /! Service 4 Area End Here
  /! Contact Banner2 Area Start Here
  .contact-banner2-area
    .container
      h2
        - if en_locale?
          | We are experts from all
          br/
          | landscaping works
        - else
          | Ми експерти з усіх
          br/
          | ландшафтних робіт
      br/
      br/
      br/
      = link_to t('navigation.gallery'), gallery_path, class: 'btn-square-transparent'
      
  .our-projects2-area
    .container
      .section-title-area.col-xs-12
        h2.section-title
          - if en_locale?
            span< S
            |uccessful
            span< P
            |rojects
          - else
            span< У
            |спішні
            span< П
            |роекти
        .title-bottom-icon
          i.fa.fa-tree aria-hidden="true" 
        p = Page['home_successfull_projects'].content.html_safe 
    
    .container
      .our-projects2-carousel.gl-carousel data-autoplay="false" data-autoplay-timeout="10000" data-dots="true" data-items="4" data-loop="true" data-margin="30" data-nav="false" data-nav-speed="false" data-r-medium="4" data-r-medium-dots="true" data-r-medium-nav="false" data-r-small="3" data-r-small-dots="true" data-r-small-nav="false" data-r-x-medium="2" data-r-x-medium-dots="true" data-r-x-medium-nav="false" data-r-x-small="1" data-r-x-small-dots="false" data-r-x-small-nav="true" data-smart-speed="2000" 
        
        - Project.limit(6).all.each do |project|
          .our-projects-box2
            .project-img-holder
              = image_tag project.image.url, class: "img-responsive", alt: project.title, style: 'max-height: 200px; object-fit: cover;'
            .project-content-holder
              h3
                a href="#" = project.title
              p = project.description

  .help-contact-banner2-area
    .container
      .row
        .col-lg-9.col-md-9.col-sm-12.col-xs-12
          h2
            - if en_locale?
              span Dream about &nbsp;
              | Beautiful Garden
              span ?&nbsp; 
              span Contact&nbsp;
              | Us
            - else
              span Мрієте про &nbsp;
              | Квітучий Сад
              span ?&nbsp; 
              span Завітайте до&nbsp;
              | Нас
        .col-lg-3.col-md-3.col-sm-12.col-xs-12.text-left
          = link_to t('navigation.contact'), contacts_path, class: 'btn-contact2'
  