config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do
    root 'welcome#index'
    resource :about, only: :show
    resource :gallery, only: :show

    resources :contacts, only: [:index, :create]
    
    namespace :admin do
      root 'dashboard#index'

      resources :settings, only: [:index, :edit, :update]
      resources :contacts, only: [:index, :show, :destroy]
      resources :pages, only: [:index, :show, :edit, :update]
      resources :projects
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Project < ApplicationRecord
  translates :title, :description
  mount_uploader :image, ProjectPhotoUploader
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def index
    @projects = collection
  end

  def show
    @project = resource
  end

  def new
    @project = Project.new
  end 

  def create
    @project = Project.create(resource_params)

    if @project.persisted?
      redirect_to [:admin, @project], flash: { success: 'Project successfully updated' }
    else
      render :new
    end
  end

  def edit
    @project = resource
  end 

  def update
    @project = resource
    if @project.update(resource_params)
      redirect_to [:admin, @project], flash: { success: 'Project successfully updated' }
    else
      render :edit
    end
  end

  def destroy
    @project = resource
    if @project.destroy
      flash[:success] = 'Project successfully deleted'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to admin_projects_path
  end 

  protected

  def collection
    Project
  end

  def resource
    collection.find(params[:id])
  end

  def resource_params
     params
      .require(:project)
      .permit(:title, :description, :image)
  end
end

app/views/admin/projects/_form.html.slim
= simple_form_for [:admin, @project] do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.input :image, as: :file
  = f.submit class: 'btn btn-secondary'

app/views/admin/projects/edit.html.slim
- breadcrumbs([{text: 'Галерея робіт', url: admin_projects_path}, {text: 'Редагування'}])

.row
  .col-lg-6
    = image_tag @project.image.thumb.url, class: 'img-responsive' if @project.image.present?
  .col-lg-6
    = render 'admin/projects/form'

app/views/admin/projects/index.html.slim
- breadcrumbs({text: 'Галерея робіт'})

.row
  .col-lg-12
    .pull-right
      = link_to new_admin_project_path, class: 'btn btn-success' do
        = fa_icon 'plus', text: 'Додати проект'
    br
    br
.row
  .col-lg-12
    .table-responsive
      table.table.table-bordered.table-hover
        thead
          tr
            th Перегляд
            th Назва
            th Опис
            th Дії
        tbody
          - @projects.all.each do |project|
            tr
              td = image_tag project.image.thumb.url, class: 'img-responsive'
              td = project.title
              td = truncate_html(project.description)
              td
                => link_to admin_project_path(project)  do
                  = fa_icon 'eye', text: 'Перегляд'
                br/
                =< link_to edit_admin_project_path(project) do
                  = fa_icon 'pencil', text: 'Редагувати'
                br/
                =< link_to admin_project_path(project), method: :delete, data: { confirm: 'Are you sure?' } do
                  = fa_icon 'trash', text: 'Видалити'

app/views/admin/projects/new.html.slim
- breadcrumbs([{text: 'Галерея робіт', url: admin_projects_path}, {text: 'Новий проект'}])

.row
  .col-lg-6
    = render 'admin/projects/form'

app/views/admin/projects/show.html.slim
- breadcrumbs([{text: 'Галерея робіт', url: admin_projects_path}, {text: @project.title}])

.row
  .col-lg-12
    .table-responsive
      table.table.table-bordered.table-hover
        tbody
          tr
            td Назва
            td = @project.title
          tr
            td Фото
            td = image_tag @project.image.thumb.url, class: 'img-responsive'
          tr
            td Опис
            td = @project.description.html_safe
          tr
            td
              =< link_to edit_admin_project_path(@project) do
                  = fa_icon 'pencil', text: 'Редагувати'
            td
              =< link_to admin_project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } do
                = fa_icon 'trash', text: 'Видалити'