config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  scope "(:locale)" do
    root 'welcome#index'
    resource :about, only: :show
    resource :gallery, only: :show

    resources :contacts, only: [:index, :create]
    
    namespace :admin do
      root 'dashboard#index'

      resources :settings, only: [:index, :edit, :update]
      resources :contacts, only: [:index, :show, :destroy]
      resources :pages, only: [:index, :show, :edit, :update]
      resources :projects
    end
  end
end

app/helpers/admin/navigation_helper.rb
module Admin::NavigationHelper
  def breadcrumbs(links = [], add_home = true)
    links = [links].flatten
    
    links.unshift({
      url: admin_root_path,
      text: 'Головна'
    }) if add_home

    page_title = links.last[:text]

    content_for(:breadcrumbs) do
      render 'admin/shared/navigation/breadcrumbs', breadcrumb_links: links, page_title: page_title
    end
  end
end

app/views/admin/shared/navigation/_breadcrumbs.html.slim
.row
  .col-lg-12
    h1.page-header
      = page_title

    - active_item = breadcrumb_links.pop
    ol.breadcrumb
      - breadcrumb_links.each do |link_item|
        li
          - if link_item.has_key?(:url)
            = link_to link_item[:text], link_item[:url]
          - else
            = link_item[:text]
        
      li.active
        = active_item[:text]

app/views/admin/shared/navigation/_header.html.slim
.navbar-header
  button.navbar-toggler.hidden-sm-up.pull-sm-right data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button" 
    | ☰
  = link_to 'Панель управління', admin_root_path, class: 'navbar-brand'
  
  ul.nav.navbar-nav.top-nav.navbar-right.pull-xs-right
    li.nav-item.buy-now
      = link_to root_path, class: "btn btn-primary-outline buy-now-btn", target: '_blank', style: 'padding: .375rem 1rem !important; border-color: #999;' do
        = "Перейти до сайту"
                

app/views/admin/shared/navigation/_sidebar.html.slim
.collapse.navbar-collapse.navbar-toggleable-sm.navbar-ex1-collapse
  ul.nav.navbar-nav.side-nav.list-group
    li.list-group-item
      = link_to admin_root_path do
        i.fa.fa-fw.fa-dashboard
        | Головна
    li.list-group-item
      = link_to admin_contacts_path do
        i.fa.fa-fw.fa-envelope-open-o
        | Повідомлення
    li.list-group-item
      = link_to admin_pages_path do
        i.fa.fa-fw.fa-book
        | Сторінки
    li.list-group-item
      = link_to admin_projects_path do
        i.fa.fa-fw.fa-file-image-o
        | Галерея робіт
    li.list-group-item
      = link_to admin_settings_path do
        i.fa.fa-fw.fa-cogs
        | Налаштування сайту
    